### ISSUE TITLE
Failed to fetch mirror+file

### ISSUE THREAD

**Issue by smarie** [MatteoH2O1999/setup-python#41]
Hi @MatteoH2O1999 , sorry to bug you again but it seems that the action stopped working : https://github.com/smarie/python-pytest-cases/actions/runs/7494807211/job/20403543648#step:3:104

```bash
Run MatteoH2O1999/setup-python@v1
Run MatteoH2O1999/build-and-install-python@4c5bdb9242b6757d60e7dc27a6b913761cad6992
CPython version >=2.7.0 <2.8.0-0 is not supported by actions/setup-python.
CPython version >=2.7.0 <2.8.0-0 will be built from source.
Version range >=2.7.0 <2.8.0-0 resolved to 2.7.18. Source code uri: https://api.github.com/repos/python/cpython/zipball/refs/tags/v2.7.18
Trying to use cached built version
Installing dependencies
  /usr/bin/sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libsqlite3-dev libncursesw5-dev libreadline-dev libgdbm-dev libgdbm-compat-dev libssl-dev curl llvm libncurses5-dev xz-utils tk-dev liblzma-dev gdb lcov pkg-config libffi-dev libreadline6-dev lzma lzma-dev uuid-dev
  
  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
  
  Reading package lists...
  Building dependency tree...
  Reading state information...
  build-essential is already the newest version (12.9ubuntu3).
  build-essential set to manually installed.
  libbz2-dev is already the newest version (1.0.8-5build1).
  libbz2-dev set to manually installed.
  libffi-dev is already the newest version (3.4.2-4).
  libffi-dev set to manually installed.
  liblzma-dev is already the newest version (5.2.5-2ubuntu1).
  liblzma-dev set to manually installed.
  libreadline-dev is already the newest version (8.1.2-1).
  libreadline-dev set to manually installed.
  make is already the newest version (4.3-4.1build1).
  pkg-config is already the newest version (0.29.2-1ubuntu3).
  uuid-dev is already the newest version (2.37.2-4ubuntu3).
  uuid-dev set to manually installed.
  xz-utils is already the newest version (5.2.5-2ubuntu1).
  curl is already the newest version (7.81.0-1ubuntu1.15).
  libsqlite3-dev is already the newest version (3.37.2-2ubuntu0.3).
  libssl-dev is already the newest version (3.0.2-0ubuntu1.12).
  zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu9.2).
  The following additional packages will be installed:
    libbabeltrace1 libboost-regex1.74.0 libc6-dbg libdebuginfod-common
    libdebuginfod1 libgd-perl libipt2 libperlio-gzip-perl
    libsource-highlight-common libsource-highlight4v5 libxft-dev libxss-dev
    llvm-runtime tcl-dev tcl8.6-dev tk8.6-dev
  Suggested packages:
    gdb-doc gdbserver tcl-doc tcl8.6-doc tk-doc tk8.6-doc
  The following NEW packages will be installed:
    gdb lcov libbabeltrace1 libboost-regex1.74.0 libc6-dbg libdebuginfod-common
    libdebuginfod1 libgd-perl libgdbm-compat-dev libgdbm-dev libipt2
    libncurses5-dev libncursesw5-dev libperlio-gzip-perl
    libsource-highlight-common libsource-highlight4v5 libxft-dev libxss-dev llvm
    llvm-runtime lzma lzma-dev tcl-dev tcl8.6-dev tk-dev tk8.6-dev
  0 upgraded, 26 newly installed, 0 to remove and 21 not upgraded.
  Need to get 21.0 MB of archives.
  After this operation, 45.2 MB of additional disk space will be used.
  Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
  Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libdebuginfod-common all 0.186-1build1 [7878 B]
  Get:3 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libbabeltrace1 amd64 1.5.8-2build1 [160 kB]
  Get:4 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libdebuginfod1 amd64 0.186-1build1 [12.7 kB]
  Get:5 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libipt2 amd64 2.0.5-1 [46.4 kB]
  Get:6 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libsource-highlight-common all 3.1.9-4.1build2 [64.5 kB]
  Get:7 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libboost-regex1.74.0 amd64 1.74.0-14ubuntu3 [511 kB]
  Get:8 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libsource-highlight4v5 amd64 3.1.9-4.1build2 [207 kB]
  Get:9 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 gdb amd64 12.1-0ubuntu1~22.04 [3919 kB]
  Get:10 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libperlio-gzip-perl amd64 0.19-1build8 [14.9 kB]
  Get:11 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 lcov all 1.15-1 [99.5 kB]
  Get:12 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgdbm-compat-dev amd64 1.23-1 [6672 B]
  Get:13 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgdbm-dev amd64 1.23-1 [117 kB]
  Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libncurses5-dev amd64 6.3-2ubuntu0.1 [790 B]
  Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libncursesw5-dev amd64 6.3-2ubuntu0.1 [790 B]
  Get:16 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libxft-dev amd64 2.3.4-1 [52.4 kB]
  Get:17 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libxss-dev amd64 1:1.2.3-1build2 [12.3 kB]
  Get:18 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 llvm-runtime amd64 1:14.0-55~exp2 [3204 B]
  Get:19 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 llvm amd64 1:14.0-55~exp2 [3758 B]
  Get:20 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 lzma amd64 9.22-2.2 [47.3 kB]
  Get:21 http://azure.archive.ubuntu.com/ubuntu jammy/universe amd64 lzma-dev all 9.22-2.2 [41.6 kB]
  Get:22 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 tcl8.6-dev amd64 8.6.12+dfsg-1build1 [1002 kB]
  Get:23 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 tcl-dev amd64 8.6.11+1build2 [5768 B]
  Get:24 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 tk8.6-dev amd64 8.6.12-1build1 [785 kB]
  Get:25 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 tk-dev amd64 8.6.11+1build2 [2904 B]
  Ign:26 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libc6-dbg amd64 2.35-0ubuntu3.5
  Get:27 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgd-perl amd64 2.76-2build1 [138 kB]
  Ign:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libc6-dbg amd64 2.35-0ubuntu3.5
  Ign:26 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 libc6-dbg amd64 2.35-0ubuntu3.5
  Err:26 mirror+file:/etc/apt/apt-mirrors.txt jammy-updates/main amd64 libc6-dbg amd64 2.35-0ubuntu3.5
    404  Not Found [IP: 52.252.75.106 80]
  Fetched 7261 kB in 1s (7112 kB/s)
  E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/g/glibc/libc6-dbg_2.35-0ubuntu3.5_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  Error: The process '/usr/bin/sudo' failed with exit code 100
      at ExecState._setResult (/home/runner/work/_actions/MatteoH2O1999/build-and-install-python/4c5bdb9242b6757d60e7dc27a6b913761cad6992/dist/index.js:9517:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/MatteoH2O1999/build-and-install-python/4c5bdb9242b6757d60e7dc27a6b913761cad6992/dist/index.js:9500:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/MatteoH2O1999/build-and-install-python/4c5bdb9242b6757d60e7dc27a6b913761cad6992/dist/index.js:9394:27)
      at ChildProcess.emit (node:events:513:28)
      at maybeClose (node:internal/child_process:1100:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
  Error: Error while building Python.
```

If you think that this has nothing to do with your action please feel free to close.
Thanks !

**Comment by MatteoH2O1999** [comment]
Are you using the latest version?

**Comment by MatteoH2O1999** [comment]
As you can see [here](https://github.com/MatteoH2O1999/setup-python/actions/runs/7496328220) it works normally.
Going to close this as it is probably related to using an obsolete version

**Comment by MatteoH2O1999** [comment]
Also please remember to use the correct template if you encounter any issues

**Comment by smarie** [comment]
Thanks a lot @MatteoH2O1999 !! It was indeed a version problem. And thanks for the hint to check and update versions!
